#!/bin/bash
FILES=$(
	git diff-index HEAD \
	| grep ".js$" \
	| grep "^:"   \
	| perl -pe 's/.*?\s[DAM]\s+//g' \
)

echo $FILES

errors=0

for file in $FILES; do

	echo "Checking $file..."
	error=$(npx babel $file 2>&1 1>/dev/null)

	RETVAL=$?

	if [[ $RETVAL != 0 ]]; then
		echo $error | sed "s,.*,    ${esc}[31m&${esc}[0m,";
		errors=1
	fi
done

if [[ $errors == 1 ]]; then
	echo "Commit aborted.";
	exit 1;
else
	exit 0;
fi
